Drive train gyro
frc2399/2017-Season pull request #5
Opened 2017-02-06 23:13 UTC by chloe6248

2017-02-08 00:20 UTC, jameshochadel requested changes

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/RobotMap.java
> +	public static final double DRIVE_MIXED_ANGULAR = 0;
I think 73-74 should have some description of what they do. (edit: I wrote this before you explained what 'mixed' meant, but I think I stand by it. 'mixed' is a good, short word for what it intends to describe, but a little note somewhere would be helpful)

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/commands/DriveAnglePAdjustment.java
> + *
A brief Javadoc should be filled out before merge. I'm not totally sure what these classes are for; I'm guessing the PID-loop tuning?

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		rightFrontTalon.setP(currentPConstant += RobotMap.DRIVE_DISTANCE_INCREMENT);
Separation of concerns = great! These are in the right place. May I suggest making this one line, though? You create the `currentPConstant` variable, then use it only once; you could simply call the function inline. Same goes for the next few methods as well.

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		return Navx.getYaw();
I'd like a javadoc that describes the return value a bit more. E.g. if the method returns `90.0`, what does that actually mean? Is it relative to the initial position? Is it clockwise or CCW? (If this is actually an obvious thing that I'm just missing, let me know and I'll clear this comment)

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		if(getCurrentAngle()-180 >= getDesiredAngle())
Note: After chatting with team, I'd like a group activity during which we simplify this method. It does work, but I am like 90% certain it can be done more simply.

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		double pOutput = calculateAngleError() * anglePConstant;
Hmm, I don't think this is how p-constants are supposed to work. Perhaps I am misunderstanding, or this is a different P from the PID loop, but that P should be fed into the Talons.

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		if(Math.abs(calculateAngleError()) <= RobotMap.DRIVE_ANGLE_ERROR)
You can shorten this to just say `return Math.abs(calculateAngleError()) <= RobotMap.DRIVE_ANGLE_ERROR`

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		double anglePOutput = calculateAngleError() * anglePConstant;
Same question as above r/e use of p-constant

2017-02-08 00:20 UTC, jameshochadel commented on .classpath
> +	<classpathentry kind="var" path="navx-mxp"/>
Just brainstorming, but it might not be a bad idea to have a "setting up the 2017-Season project" document somewhere; a README in the project repo would be perfect for this! (It'd be pretty simple; just point them to the WPI 2017 System Update stuff and the notes you made in the journals for installing this)

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/commands/DriveAnglePAdjustment.java
> +    public DriveAnglePAdjustment(boolean isIncrementing) {
Good param naming!

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/commands/DriveDistancePAdjustment.java
> + *
Same as last one - brief Javadoc plz

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/commands/DriveDistancePAdjustment.java
> +    	if(isIncrementing == true)
Line 29 can be simpler! (I will leave the simplification as an exercise to the reader)

2017-02-08 00:20 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/commands/DriveAnglePAdjustment.java
> +    	if(isIncrementing == true)
Line 29 can be simpler! (I will leave the simplification as an exercise to the reader)

2017-02-08 01:03 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		return Navx.getYaw();
Update: See http://www.kauailabs.com/public_files/navx-mxp/apidocs/java/ -> AHRS -> getYaw; return value is in range (-180.0, 180.0).

2017-02-09 16:55 UTC, wmarshall requested changes
This still needs some work. Not much, in that I think we should move it towards testing ASAP, to validate that our NavX works, but enough that it should not be merged in current state.

2017-02-09 16:55 UTC, wmarshall commented on src/org/usfirst/frc/team2399/robot/OI.java
> +	private static Button driveAngleDecrementButt = new JoystickButton(shooterJoy, 4);
Why are we adjusting drive constants on the shooter joystick? Not a fail, just a question.

2017-02-09 16:55 UTC, wmarshall commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		if(getCurrentAngle()-180 >= getDesiredAngle())
Ah. Shortest-path angle measurement. There's a way to do this with one conditional, but it's very unintuitive unless you've written this method for a bunch of different projects. Would be happy to help with this.

2017-02-09 16:55 UTC, wmarshall commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		double pOutput = calculateAngleError() * anglePConstant;
This is actually okay. The reason that this is done here vs on the talons is that the control loop specified by this method deals with steering (left/right) while the talons are only aware of velocity (forward/back). Steering is an abstraction over velocity, so it makes sense to sit higher in the abstraction pyramid

2017-02-09 16:55 UTC, wmarshall commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		driveLeftVelocity(pOutput);
Why the +/-? what coordinate system are we using? Looks like CW = + , but this isn't documented anywhere.

2017-02-09 16:55 UTC, wmarshall commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		double anglePOutput = calculateAngleError() * anglePConstant;
Same answer as above

2017-02-09 17:43 UTC, jameshochadel commented on src/org/usfirst/frc/team2399/robot/subsystems/DriveTrain.java
> +		double pOutput = calculateAngleError() * anglePConstant;
Yep, I checked in with Chloe and that makes sense. (I really wish these comments had a 'resolve' button)

2017-02-15 23:37 UTC, merged